#ifndef __INTRINSIC_SIZES_H
#define __INTRINSIC_SIZES_H
#define SIZEOF_INTEGER 4
#define SIZEOF_CHARACTER 1
#define SIZEOF_REAL 4
#define SIZEOF_DOUBLE_COMPLEX 16
#define SIZEOF_DOUBLE_PRECISION 8
#endif
