name: Build Deploy Containers

on:

  # Publish packages on release
  release:
    types: [published]

  pull_request: []

  # On push to main we build and deploy images
  push:
    branches:
    - main

jobs:
  build:
    permissions:
      packages: write

    env:
      container: ghcr.io/magic-sph/magic
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Container
      run: docker build -t ${{ env.container }} .

    - name: GHCR Login
      if: (github.event_name != 'pull_request')
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and Push Release Image
      if: (github.event_name == 'release')
      run: |
        tag=${GITHUB_REF#refs/tags/}
        echo "Tagging and releasing ${{ env.container }}:${tag}"
        docker tag ${{ env.container }}:latest ${{ env.container }}:${tag}
        docker push ${{ env.container }}:${tag}

    - name: Deploy
      if: (github.event_name != 'pull_request')
      run: docker push ${{ env.container }}:latest
