# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Test shell
        run: echo "MagIC auto test with shell type $SHELL"

      # Runs a set of commands using the runners shell
      - name: Install pre-requisites
        run: |
          sudo apt-get -y install gfortran gcc g++ cmake liblapack-dev libgomp1
          sudo apt-get -y install mpich libmpich-dev
          sudo apt-get -y install python3-gi python3-gi-cairo gir1.2-gtk-3.0
          wget https://bootstrap.pypa.io/get-pip.py
          python3 get-pip.py
          export PATH=$HOME/.local/bin:$PATH
          python3 -m pip install numpy scipy matplotlib --user

      - name: Run test
        run: |
          ulimit -s unlimited
          source sourceme.sh
          export FC=mpif90
          export CC=mpicc
          export CXX=mpicxx
          cd ${{github.workspace}}/samples
          export OMP_NUM_THREADS=1
          python3 magic_wizard.py --use-mpi --nranks 2 --level 0 --mpicmd mpiexec.hydra
